version: '3.8'

services:
  mtproxy:
    build: .
    container_name: mtproxy
    restart: unless-stopped
    ports:
      - "1443:1443"   # MTProto порт
      - "8888:8888"   # Статистика
    volumes:
      - ./secret:/secret:ro
      - ./proxy-secret:/proxy-secret:ro
      - ./proxy-multi.conf:/proxy-multi.conf:ro
    command: >
      -u nobody
      -p 8888
      -H 1443
      -S $(cat /secret)
      --aes-pwd /proxy-secret /proxy-multi.conf
      -M 1
