services:
  mtproxy:
    build: .
    container_name: mtproxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MT_PORT:-1443}:${MT_PORT:-1443}"           # MTProto
      - "127.0.0.1:${MT_STATS_PORT:-8888}:${MT_STATS_PORT:-8888}"  # Статистика только localhost
    volumes:
      - ./data:/var/lib/mtproxy
